### PR TITLE
fix: #https://github.com/gurleensethi/sailor/issues/34

### PR DESCRIPTION
**Pull request by Kiruel**
Fix the https://github.com/gurleensethi/sailor/issues/34

### CODE REVIEW

**Comment by Kiruel** [comment]
@gurleensethi Waiting for review.

**Comment by deadsoul44** [comment]
@gurleensethi could you please check?

**Comment by gabrielintang** [comment]
hi @gurleensethi I think we need this fix

**Comment by ghost** [comment]
This is now breaking on beta channel as well. This fix is needed to many developers now.

**Comment by deadsoul44** [comment]
Replace sailor in pubspec.yaml with the following part:
```
  sailor:
    git:
      url: git://github.com/Kiruel/sailor.git
      ref: master
```
You don't need any other change. 
Thanks to @Kiruel

**Comment by gurleensethi** [comment]
Thanks @Kiruel for the pull request.

**Pull request closed without merging**
