### PR TITLE
Fix null exception where params (not required) are not passed but def…

### PR DESCRIPTION
**Pull request by arielbh**
…ined
A fix for this issue: https://github.com/gurleensethi/sailor/issues/17

### CODE REVIEW

**Comment by arielbh** [comment]
@gurleensethi Hi! need any clarifications about this PR?
Thanks!

**Comment by arielbh** [comment]
@gurleensethi Just checking out that all is well, and this repo is not abandoned :/

**Comment by haqqi** [comment]
@arielbh aw, seems like @gurleensethi is too busy to maintain this repo.

**Comment by arielbh** [comment]
Perhaps @gurleensethi can add more people to assist him in maintaining this repo?

**Pull request closed without merging**
